<?php

namespace WebsiteBundle\Repository;

/**
 * Ticket2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ticket2Repository extends \Doctrine\ORM\EntityRepository
{
}
