website:
    resource: "@WebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

menu:
    resource: "@MenuBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

#Redirection en cas de success
add_ticket_success:
    path: /add-ticket-success
    defaults: { _controller: WebsiteBundle:GestionTicket:addTicketSuccess}
